### ISSUE TITLE
Bug: Undo button

### ISSUE THREAD

**Issue by ching23** [Devamp/StrategoFramework#12]
Clicking the undo turn button doesn’t undo the turn of the user’s move. If the user chooses to move a piece forward/capture, then clicks on the undo turn button to undo their move, the user is allowed to move again, but the piece doesn’t return to its spot before the move was made. With the bug, the user can continuously advance their pieces forward then click the undo turn button to “skip” the computer players turn. The user then has an advantage because the computer player’s pieces don’t move.

**Comment by devamp** [comment]
We just had the code for undo commented out. We fixed it, thanks!
