### ISSUE TITLE
Bug: changing orientation

### ISSUE THREAD

**Issue by inouyeg23** [Devamp/StrategoFramework#16]
currently the game is only half playable when switching orientation from horizontal to vertical.  When I changed the orientation, only half of the board was displayed, the buttons were skewed and for some reason the timer was counting faster (I don't understand why changing the orientation messes with the timer so this is kinda funny to me).  I'm having the same issue in my own game so I'm interested in how you guys can fix this

**Comment by devamp** [comment]
We stated in our design presentation that our game will be restricted to landscape mode only. Thanks for pointing this out. We have fixed the issue and our game is now only playable in landscape. If you are curious, add "android:screenOrientation="reverseLandscape"" inside your AndroidManifest.xml under the <activity> category.
